spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/axenix-learning-java-up
    username: postgres
    password: Danifrenchplay23
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
  liquibase:
    change-log: classpath:liquibase/root-changelog.xml

application-service-config:
  project-success: 0.9

server:
  port: 8090